# INFINITE OS GSI product

PRODUCT_NAME := infinite_gsi
PRODUCT_DEVICE := infinite_gsi
PRODUCT_BRAND := INFINITE
PRODUCT_MANUFACTURER := INFINITE
PRODUCT_MODEL := INFINITE OS GSI

INFINITE_OS_VERSION := 1.0
INFINITE_BUILD_ID := INFINITE-GSI-001
