# INFINITE OS default configuration

PRODUCT_BRAND := INFINITE
PRODUCT_MANUFACTURER := INFINITE
PRODUCT_MODEL := INFINITE DEVICE
PRODUCT_NAME := infinite
PRODUCT_DEVICE := infinite

INFINITE_OS_VERSION := 1.0
INFINITE_BUILD_ID := INFINITE-001
